import { clr } from "clr.slint";

export component Setting inherits Rectangle {
    in-out property <bool> appear: false;
    background: clr.bg;

    Text {
        text: "设置";
        color: clr.txt;
        font-size: 75px;
        x: 20px;
        y: 30px;
    }

    Rectangle {
        x: 620px;
        y: 180px;
        width: 430px;
        height: 96px;
        background: clr.card;
        border-radius: 18px;

        Text {
            text: "深色模式";
            color: clr.txt;
            font-size: 30px;
            x: 22px;
            y: 28px;
        }

        Rectangle {
            x: 290px;
            y: 20px;
            width: 110px;
            height: 56px;
            background: clr.chgthm ? #22c55e : clr.off;
            border-radius: 28px;
        }

        Rectangle {
            x: clr.chgthm ? 350px : 300px;
            y: 26px;
            width: 44px;
            height: 44px;
            background: clr.on;
            border-radius: 22px;
            animate x { duration: 180ms; }
        }

        TouchArea {
            clicked => {
                clr.chgthm = !clr.chgthm;
            }
        }
    }

    Rectangle {
        x: 620px;
        y: 300px;
        width: 430px;
        height: 96px;
        background: clr.card;
        border-radius: 18px;

        Text {
            text: "动画";
            color: clr.txt;
            font-size: 30px;
            x: 22px;
            y: 28px;
        }

        Rectangle {
            x: 290px;
            y: 20px;
            width: 110px;
            height: 56px;
            background: clr.sw;
            border-radius: 28px;
        }

        Rectangle {
            x: clr.anim ? 350px : 300px;
            y: 26px;
            width: 44px;
            height: 44px;
            background: clr.on;
            border-radius: 22px;
            animate x { duration: 180ms; }
        }

        TouchArea {
            clicked => {
                clr.anim = !clr.anim;
            }
        }
    }
}
